howto/config/routes.rb
Howto::Application.routes.draw do
  resources :clubs

  resources :classements

  resources :mon_equipes
  
  resources :transferts
  
  resources :entrainemets

  resources :contrats

  resources :staffs

  resources :saisons

  resources :divisions do
    resource :list
  end

  resources :historiques

  resources :equipes 
	
  resources :joueurs

  resources :user_sessions

  resources :users

 resources :mon_equipe 
 
 resources :stats
 
  match "login", :controller => "user_sessions", :action => "new", :via => [:post]
  match "logout", :controller => "user_sessions", :action => "destroy", :via => [:get, :post]
  match "test" , :controller => "equipes", :action => "test", :via => [:get, :post]
  match "update_transfert", :controller => "transferts", :action =>"update_transfert", :via => [:get, :post]

	root :controller => :mon_equipe, :action => :index

  match ':controller(/:action(/:id))(.:format)', :via => [:get, :post]
end

howto/app/models/equipe.rb
class Equipe < ActiveRecord::Base
has_many :joueurs
belongs_to :club
end

howto/app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
 respond_to :html
  def test
  @classement = Classement.find_by_sql(["SELECT equipes.nom as equipe, equipes.id as equipeID, points, victoire,defaite,nul,bp,bc, nb_journee,
										divisions.nom ,divisions.id as divID
										FROM equipes, historiques, saisons, classements, divisions
										WHERE historiques.id = classements.historique_id 
										AND historiques.saison_id = saisons.id
										AND equipes.id = historiques.equipe_id
										AND saisons.division_id = divisions.id
										AND saisons.division_id = (SELECT saisons.division_id FROM equipes, historiques, saisons
										WHERE historiques.saison_id = saisons.id
										AND historiques.equipe_id = equipes.id
										AND equipes.id = ?)  ORDER BY points DESC,(bp-bc) DESC", 1])
	@agenda = Saison.find_by_sql(["SELECT equipe1.nom AS equipe1Nom, equipe2.nom equipe2Nom,  matchs.score1, matchs.score2,
										matchs.num_journee,matchs.id, matchs.equipe1_id as equipe1ID , matchs.equipe2_id  as equipe2ID
									FROM equipes AS equipe1, equipes AS equipe2, matchs, saisons, annees
									WHERE matchs.saison_id = saisons.id
									AND matchs.num_journee = annees.journee
									AND equipe2.id = matchs.equipe2_id
									AND equipe1.id = matchs.equipe1_id
									AND saisons.division_id = (
									SELECT saisons.division_id
									FROM equipes, historiques, saisons
									WHERE historiques.saison_id = saisons.id
									AND historiques.equipe_id = equipes.id
									AND equipes.id =?)",  1])

	@calendrier = Saison.find_by_sql(["SELECT equipe1.nom AS equipe1Nom, matchs.score1, matchs.score2, equipe2.nom  AS equipe2Nom, 
										matchs.num_journee,matchs.id  , equipe1.id as equipe1ID , equipe2.id  as equipe2ID  
									FROM equipes AS equipe1, equipes AS equipe2, matchs, saisons
									WHERE matchs.saison_id = saisons.id
									AND equipe2.id = matchs.equipe2_id
									AND equipe1.id = matchs.equipe1_id
									AND (equipe1.id = ?
									OR	equipe2.id = ?)
									AND saisons.division_id = (
									SELECT saisons.division_id
									FROM equipes, historiques, saisons
									WHERE historiques.saison_id = saisons.id
									AND historiques.equipe_id = equipes.id
									AND equipes.id =?)",  1 ,  1,  1])

  
  
   if not current_user
	@user_session = UserSession.new
  end
  
  
  @couleur1 = Club.find_by_sql(["SELECT clubs.couleur1 as couleur1, clubs.couleur2 as couleur2 
								FROM equipes, clubs, matchs
								WHERE equipes.club_id = clubs.id
								AND equipes.id = matchs.equipe1_id
								AND matchs.id = ?", 114])
	
	@couleur2 = Club.find_by_sql(["SELECT clubs.couleur1 as couleur1, clubs.couleur2 as couleur2 
								FROM equipes, clubs, matchs
								WHERE equipes.club_id = clubs.id
								AND equipes.id = matchs.equipe2_id
								AND matchs.id = ?", 114])
  
    
  # On cherche l'id de la tactique de l'equipe1
	@fdm1 = Saison.find_by_sql(["SELECT tactique_equipe1
									FROM matchs
									WHERE id = ?", 114])
	tact1_id = @fdm1[0].tactique_equipe1

# S'il y a deja une tactique, on a la charge
@tact1=[]
@remp1=[]
if tact1_id != nil
	(1..11).each do |i|
	 @tact1[i] = Saison.find_by_sql(["SELECT positions.x as posx, id_joueur, numero,positions.y as posy FROM tactiques, positions, joueurs
								WHERE tactiques.position_j#{i}_id = positions.id
								AND positions.id_joueur = joueurs.id
								AND tactiques.id = ?",tact1_id ])
	end
	(1..5).each do |i|
	 @remp1[i] = Saison.find_by_sql(["SELECT remplacant#{i}_id as idRemp, numero FROM tactiques, joueurs
								WHERE remplacant#{i}_id = joueurs.id
								AND tactiques.id = ?",tact1_id ])
	end
end

# On cherche l'id de la tactique de l'equipe2
	@fdm2 = Saison.find_by_sql(["SELECT tactique_equipe2
									FROM matchs
									WHERE id = ?", 114])
	tact2_id = @fdm2[0].tactique_equipe2

# S'il y a deja une tactique, on a la charge
@tact2=[]
@remp2=[]
if tact2_id != nil
	(1..11).each do |i|
	 @tact2[i] = Saison.find_by_sql(["SELECT positions.x as posx, id_joueur, numero,positions.y as posy FROM tactiques, positions, joueurs
								WHERE tactiques.position_j#{i}_id = positions.id
								AND positions.id_joueur = joueurs.id
								AND tactiques.id = ?",tact2_id ])
	end
	(1..5).each do |i|
	 @remp2[i] = Saison.find_by_sql(["SELECT remplacant#{i}_id as idRemp, numero FROM tactiques, joueurs
								WHERE remplacant#{i}_id = joueurs.id
								AND tactiques.id = ?",tact2_id ])
	end
end

  end
  
  
  
  
  
  def index
    @equipes = Equipe.all
     if not current_user
	@user_session = UserSession.new
  end
  end

  def show
  
  if params[:id].to_i == current_team
	if request.xhr?
		  # respond to Ajax request
			render :layout => false
	end
  
   redirect_to '/'
  
  else
  @login = Equipe.find_by_sql(["SELECT users.login as login, users.email as email FROM users
								 WHERE users.equipe_id = ?", params[:id]]);
								 
    	#TODO rajouter le filtre pour trouver les joueurs dont la date de in de contrat < date courante
    #@joueurs = Joueur.find(:all, :include => [:equipes => :contrats], 
     #               		 :conditions => ["equipes.id = ?", params[:id]], :order=>"numero")
     
  @joueurs = Joueur.find_by_sql (["SELECT joueurs. * , count( stats.id_joueur ) AS nbmatch, avg( stats.note ) AS avgnote, (
										SELECT stats.note AS lastnote
										FROM stats, joueurs
										WHERE stats.id_joueur = joueurs.id
										ORDER BY stats.id DESC
										LIMIT 1
										) AS lastnote
										FROM joueurs
										LEFT OUTER JOIN stats ON joueurs.id = stats.id_joueur, equipes
										WHERE equipes.id = ?
										AND equipes.id = joueurs.equipe_id
										GROUP BY joueurs.id
										ORDER BY joueurs.numero", params[:id]])
     
     
    @couleur = Club.find_by_sql(["SELECT clubs.couleur1 as couleur1, clubs.couleur2 as couleur2 FROM equipes, clubs
								WHERE equipes.club_id = clubs.id
								AND equipes.id = ?", params[:id]])
	
 #On cherche l'id de la tactique de l'equipe
@match = Equipe.find_by_sql(["SELECT matchs.id, matchs.equipe1_id, matchs.equipe2_id
									FROM matchs, annees
									WHERE num_journee = annees.journee
									AND (equipe1_id =? OR equipe2_id =?)",  params[:id], params[:id]])

if @match[0].equipe1_id == params[:id].to_i
	@fdm = Equipe.find_by_sql(["SELECT tactique_equipe1
									FROM matchs
									WHERE id = ?", @match[0].id])
	tact_id = @fdm[0].tactique_equipe1
else
	@fdm= Equipe.find_by_sql(["SELECT tactique_equipe2
									FROM matchs
									WHERE id = ?", @match[0].id])
	tact_id = @fdm[0].tactique_equipe2
end

# S'il y a deja une tactique, on a la charge
@tact=[]
@remp=[]
if tact_id != nil
	(1..11).each do |i|
	 @tact[i] = Equipe.find_by_sql(["SELECT positions.x as posx, id_joueur, numero,positions.y as posy FROM tactiques, positions, joueurs
								WHERE tactiques.position_j#{i}_id = positions.id
								AND positions.id_joueur = joueurs.id
								AND tactiques.id = ?",tact_id ])
	end
	(1..5).each do |i|
	 @remp[i] = Equipe.find_by_sql(["SELECT remplacant#{i}_id as idRemp, numero FROM tactiques, joueurs
								WHERE remplacant#{i}_id = joueurs.id
								AND tactiques.id = ?",tact_id ])
	end
end
end
  
  
   if not current_user
	@user_session = UserSession.new
  end
  
  if request.xhr?
		  # respond to Ajax request
			render :layout => false
  else
		@classement = Classement.find_by_sql(["SELECT equipes.nom as equipe, equipes.id as equipeID, points, victoire,defaite,nul,bp,bc, nb_journee,
										divisions.nom ,divisions.id as divID
										FROM equipes, classements, divisions, clubs
										WHERE clubs.id = classements.club_id 
										AND equipes.club_id = clubs.id
										AND clubs.division_id = divisions.id
										AND divisions.id = (SELECT clubs.division_id FROM clubs, equipes
										WHERE equipes.club_id = clubs.id
										AND equipes.id = ?)  ORDER BY points DESC,(bp-bc) DESC",  params[:id]])
										
	@agenda = Equipe.find_by_sql(["SELECT equipe1.nom AS equipe1Nom, equipe2.nom equipe2Nom,  matchs.score1, matchs.score2,
									matchs.num_journee,matchs.id, matchs.equipe1_id as equipe1ID , matchs.equipe2_id  as equipe2ID
									FROM equipes AS equipe1, equipes AS equipe2, matchs,  annees
									WHERE matchs.num_journee = annees.journee
									AND equipe2.id = matchs.equipe2_id
									AND equipe1.id = matchs.equipe1_id"])

	@calendrier = Equipe.find_by_sql(["SELECT equipe1.nom AS equipe1Nom, matchs.score1, matchs.score2, equipe2.nom  AS equipe2Nom, 
										matchs.num_journee,matchs.id  , equipe1.id as equipe1ID , equipe2.id  as equipe2ID  
									FROM equipes AS equipe1, equipes AS equipe2, matchs
									WHERE equipe2.id = matchs.equipe2_id
									AND equipe1.id = matchs.equipe1_id
									AND (equipe1.id = ?
									OR	equipe2.id = ?)",  params[:id] ,  params[:id]])
 
  end
  
  
  end
end

howto/app/helpers/equipes_helper.rb
# Methods added to this helper will be available to all templates in the application.
module EquipesHelper

  # Retourner un titre basé sur la page.
  def titre
    base_titre = "How to manage my football team ?"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

howto/app/views/equipes/edit.html.erb
<h1>Editing equipe</h1>

<% form_for(@equipe) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @equipe %> |
<%= link_to 'Back', equipes_path %>

howto/app/views/equipes/index.html.erb
<h1>Listing equipes</h1>

<ul>
<% for equipe in @equipes %>
    <li><%= link_to equipe.nom, equipe %></li>
<% end %>
</ul>

howto/app/views/equipes/new.html.erb
<h1>New equipe</h1>

<% form_for(@equipe) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', equipes_path %>

howto/app/views/equipes/show.html.erb
<% 
	@joueur_numero=[]
	@remp_numero=[]
	@tact.each do |pos|
		unless pos.blank?
			@joueur_numero.push(pos[0].numero)
		end	
	end
	@remp.each do |pos|
		unless pos.blank?
			@remp_numero.push(pos[0].numero)
		end	
	end
 %>
 <script language="Javascript"> 
    $("#equipe_tab").bind("ajax:success", function(data, status, xhr) {
        console.log("ajax:success2");
         $(".equipe").html(status);
        checkboxInit(<%=  raw(@tact.to_json) %>,<%=  raw( @remp.to_json) %>);
        terrainInit();
		playerInit(<%=  raw(@tact.to_json) %>,<%=  raw( @remp.to_json) %> ,<%= raw( @couleur.to_json) %>);
});

$("#equipe_tab_adverse").bind("ajax:success", function(data, status, xhr) {
		$(".equipe").html(status);
        checkboxInit(<%=  raw(@tact.to_json) %>,<%=  raw( @remp.to_json) %>);
        terrainInit();
		playerInit(<%=  raw(@tact.to_json) %>,<%=  raw( @remp.to_json) %> ,<%= raw( @couleur.to_json) %>);

});
</script>

<%if not current_user %>		
		<div id="top">
			<p><strong>Bienvenu</strong> sur "How to manage my football team" qui est jeu en ligne totalement gratuit qui se joue entiérement dans votre navigateur, sans aucune
			installation de logiciel. Le jeu et le site ne sont pas encore en version finale, mais on peut jouer et les championnats ont déjà commencé. C'est un 
			jeu de gestion sportive de football autrement appelé jeux d'entraineur ou de football manager. Vous allez prendre en main le destin d'une équipe, sa
			vingtaine de bonhommes avec un championnat à remporter. Le jeu est concu pour que vos préocupations du jeu se rapproche le plus de ce que peut vivre 
			un homme de terrain, proche du rectangle vert. Créez votre tactique, sélectionnez les meilleurs joueurs, et croisez les doigts les jours de matchs. 
			Les matchs ont lieu tout les 3, 4 jours. Puis viendront la gestion de l'entrainement et des transferts.</p>
			<p>Inscrivez-vous et commencez l'aventure ou profitez de l'équipe démo pour faire le tour du jeu et des possibilités. Plus d'information et d'aides 
			disponible dans la rubrique <a href="./howto" target="_blank">how to </a>, et un rapide manuel d'uilisation est <a href="/images/manuel.png" target="_blank">ici</a>
			</p>
			<p>
				<strong>Bon jeu et bon matchs!</strong>
			</p>
		</div>
		<% else %>
		
<% end %>
<table class="tablesorter" valign="MIDDLE" align="center" border="0"  id="myTable">
	 <THEAD >
<tr>
<th style="margin-bottom:10px;">
#
</th>
<th class="stats">
<%= image_tag "icone_tactique.png", :alt => "tactique", :class => 'stats' %>
</th>
<th>

</th>
<th>

</th>
<th class="stats">
<%= image_tag "moral.png", :alt => "moral",:title=>"moral", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "condition.png", :alt => "condition",:title=>"condition", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "icone_terrain_gch.png", :alt => "gauche",:title=>"couloir gauche", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "icone_terrain_ctr.png", :alt => "centre",:title=>"zone axiale", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "icone_terrain_drt.png", :alt => "droite",:title=>"couloir droit", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "icone_terrain_off.png", :alt => "offensif",:title=>"zone offensive", :class => 'stats' %>
</th>
<th class="stats">
<%= image_tag "icone_terrain_def.png", :alt => "defensif",:title=>"zone défensive", :class => 'stats' %>
</th>
<th class="stats">
____<BR>Note
</th>
<th class="stats" width=40px; >
Note<BR/>
</th>
<th class="stats">
Mchs</th>
</tr>
</THEAD>
<TBODY>


<% i=1 %>
<% @joueurs.each do |joueur| %>

<% 
trouve=false;
couleur_nom=""
@joueur_numero.each do |numero|
	if numero == joueur.numero
		trouve = true
	end
end
@remp_numero.each do |numero|
	if numero == joueur.numero
		trouve = true
	end
end
if trouve == true
	couleur_nom = "selected"
else
	couleur_nom = "unselected"
end
trouve=false;
%>


<% if (i % 2 == 1) %>
<% @classe = "equipe_impaire" %>
<% else %>
<% @classe = "equipe_paire" %>
<% end %>
<tr class ="<%= @classe %>" id="tr_<%= joueur.id%>">
<td nowrap ALIGN="center" VALIGN ="MIDDLE" class=" <%= couleur_nom %>"> <%= joueur.numero %></td>
<td>
<% if current_user %>
	<% if current_team  == params[:id].to_i || request.path == '/' || request.path == "/mon_equipe" %>
		<%= check_box_tag(joueur.id, joueur.id, false, :onclick=>"addPlayerToField(#{joueur.gch}, #{joueur.ctr},#{joueur.drt},#{joueur.off},#{joueur.def},#{@couleur[0].couleur1},#{@couleur[0].couleur2},#{joueur.numero},this);")%>
	<% else %>
		<%= check_box_tag(joueur.id, joueur.id, false, :disabled => 'true' )%>
	<% end %>
<% else %>
	<%= check_box_tag(joueur.id, joueur.id, false, :onclick=>"addPlayerToField(#{joueur.gch}, #{joueur.ctr},#{joueur.drt},#{joueur.off},#{joueur.def},#{@couleur[0].couleur1},#{@couleur[0].couleur2},#{joueur.numero},this);")%>
<% end %>

</td>

<td nowrap ALIGN="left" VALIGN ="MIDDLE" class=" <%= couleur_nom %>" ><%= link_to joueur.nom + ' ' + joueur.prenom, joueur, remote: true , :class =>'joueur' %> </td>
<td nowrap ALIGN="center" VALIGN ="MIDDLE" class=" <%= couleur_nom %>"> <%= joueur.age %> ans </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.moral %>%"></div><div class="barfiller" style="left:<%= 100-joueur.moral %>%"></div> </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.cond %>%"></div><div class="barfiller" style="left:<%= 100-joueur.cond %>%"></div> </td>

<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.gch %>%"></div><div class="barfiller" style="left:<%= 100-joueur.gch %>%"></div> </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.ctr %>%"></div><div class="barfiller" style="left:<%= 100-joueur.ctr %>%"></div> </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.drt %>%"></div><div class="barfiller" style="left:<%= 100-joueur.drt %>%"></div> </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.off %>%"></div><div class="barfiller" style="left:<%= 100-joueur.off %>%"></div> </td>
<td class="graph" ALIGN="left" VALIGN ="MIDDLE"><div class="bar" style="width:<%= joueur.def %>%"></div><div class="barfiller" style="left:<%= 100-joueur.def %>%"></div> </td>
<td ALIGN="CENTER" VALIGN ="MIDDLE" class=" <%= couleur_nom %>"><%=joueur.avgnote%></td>
<td ALIGN="CENTER" VALIGN ="MIDDLE" class=" <%= couleur_nom %>"><%=joueur.lastnote%></td>
<td ALIGN="CENTER" VALIGN ="MIDDLE" class=" <%= couleur_nom %>"><%=joueur.nbmatch%></td>

</tr>
<% i = i + 1 %>
<% end %>
</TBODY>
</table>
<div align="center">
<div id="terrain">
</div>
</div>


<div class="bouton_div">
<%= form_tag  '/mon_equipe/valider', :id=>'equipe' do %>
<% (1..11).each do |i| %>
	<%=  hidden_field_tag("j_#{i}") %>
	<%=  hidden_field_tag("jx_#{i}") %>
	<%=  hidden_field_tag("jy_#{i}") %>
<% end %>
<% (1..5).each do |i| %>
	<%=  hidden_field_tag("r_#{i}") %>
<% end %>
<% if current_user %>
<% if current_team  == params[:id].to_i || request.path == '/' || request.path == "/mon_equipe" %>
<%= submit_tag  "Valider", {:class => 'bouton',
						   :onclick=>"valider_form()"} %>
<% else %>
<%= submit_tag  "Valider",{:disabled => 'true',
						   :class => 'bouton'} %>
<% end %>
<% end %>
<%= button_to  "Charger", {},{:disabled => 'true' ,:class => 'bouton'}%>
<%= button_to  "Enregistrer sous...", {},{:disabled => true,:class => 'bouton'} %>

<% end %>
</div>

howto/app/views/equipes/test.html.erb
Ceci est un test!!

<span id="m"></span>
<div align="center">
<div id="terrain">
</div>
</div>
<BR>

<div align="right" class="bouton">


Vitesse : <INPUT type=radio name="vitesse" value="1"  onclick="chg_vitesse(1);" checked/>x1<INPUT type=radio name="vitesse" value="10"  onclick="chg_vitesse(10);" />x10 <INPUT type=radio name="vitesse" value="20"  onclick="chg_vitesse(20);" />x20 <INPUT type=radio name="vitesse" value="50"  onclick="chg_vitesse(50);" />x50
<%= button_to "Jouer", "javascript:jouer_test()" %>
<%= button_to "Placer", "javascript:charger_test()" %>
<%= button_to "Charger Tactiques", "javascript:playerInit1( #{@tact1.to_json} ,#{@remp1.to_json}, #{@couleur1.to_json});playerInit2(#{@tact2.to_json},#{@remp2.to_json},#{@couleur2.to_json})" %>





</div>